### ISSUE TITLE
[PE-D] Unable to add a item with a cost in double format (as opposed to integer format). 

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-F12-2/tp#83] opened 2022-04-01 15:09 UTC
![image.png](https://raw.githubusercontent.com/zhenster/ped/main/files/cb50612f-b555-460d-afe4-595d794d68c8.png)
If the user wants to enter a piece of equipment with a cost that is not a whole number, there is an error output stating that the equipment was unable to be added because one or more than one of the attributes are missing. I know that `COST` may not contain any symbols, but if so, is it possible to enter a cost that's in double format? 

![image.png](https://raw.githubusercontent.com/zhenster/ped/main/files/2ebc5699-d9ae-4449-b09a-765668f72ec4.png)
The application says that the cost should be able to be parsed as a double, which indicates that the user should be able to enter doubles. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: zhenster/ped#2

**Comment by Bryan-BC** [comment] 2022-04-03 15:23
Duplicate of #100

**Closed as completed by Bryan-BC** 2022-04-03 15:23 UTC
