### ISSUE TITLE
[PE-D] Incorrect error reported to the user when user fails to include the "pf" field

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-F12-2/tp#86] opened 2022-04-01 15:12 UTC
![image.png](https://raw.githubusercontent.com/zhenster/ped/main/files/b72edf9d-285b-4e9b-a4a0-de7c4851d25c.png)
If the user leaves the "pf" field empty, the application reports that there is a problem with the cost field instead. 

![image.png](https://raw.githubusercontent.com/zhenster/ped/main/files/fad9b6d0-8583-4888-b927-62cbffa0f9c7.png)
However, if the slash is added after "pf," the correct error is thrown. Consider implementing consistent error messages regardless of whether the "/" is included. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: zhenster/ped#4

**Comment by shunyao643** [comment] 2022-04-03 15:33
Duplicate of #90

**Closed as completed** 2022-04-03 15:33 UTC
